.TH "D:/gitt/bsp_XerolySkinner/bsp_device/bsp_SPI.h" 3 "2023年 三月 9日 星期四" "Version 1.0.0" "bsp_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/bsp_XerolySkinner/bsp_device/bsp_SPI.h \- SPI的库  

.SH SYNOPSIS
.br
.PP
\fC#include <reg52\&.h>\fP
.br
\fC#include <intrins\&.h>\fP
.br

.SS "函数"

.in +1c
.ti -1c
.RI "void \fBSPI_WriteOneByte\fP (unsigned char address, unsigned char dat)"
.br
.RI "使用总线发送一个字节数据 "
.ti -1c
.RI "unsigned char \fBSPI_ReadOneByte\fP (unsigned char address)"
.br
.RI "使用总线获取一个字节数据 "
.in -1c
.SS "变量"

.in +1c
.ti -1c
.RI "sbit \fBSPI_SCK_PIN\fP = P3^6"
.br
.RI "定义SCK的管脚 "
.ti -1c
.RI "sbit \fBSPI_SDA_PIN\fP = P3^4"
.br
.RI "定义SDA的管脚 "
.ti -1c
.RI "sbit \fBSPI_RST_PIN\fP = P3^5"
.br
.RI "定义RST的管脚 "
.in -1c
.SH "详细描述"
.PP 
SPI的库 


.PP
在文件 \fBbsp_SPI\&.h\fP 中定义\&.
.SH "函数说明"
.PP 
.SS "unsigned char SPI_ReadOneByte (unsigned char address)"

.PP
使用总线获取一个字节数据 
.PP
\fB参数\fP
.RS 4
\fIaddr\fP 需要接收的寄存器地址 
.br
\fIdat\fP 接受的数据 
.RE
.PP
\fB返回\fP
.RS 4
无返回值 
.RE
.PP

.PP
在文件 \fBbsp_SPI\&.c\fP 第 \fB71\fP 行定义\&.
.SS "void SPI_WriteOneByte (unsigned char address, unsigned char dat)"

.PP
使用总线发送一个字节数据 
.PP
\fB参数\fP
.RS 4
\fIaddr\fP 需要改写的寄存器地址 
.br
\fIdat\fP 改写的数据 
.RE
.PP
\fB返回\fP
.RS 4
无返回值 
.RE
.PP

.PP
在文件 \fBbsp_SPI\&.c\fP 第 \fB57\fP 行定义\&.
.SH "变量说明"
.PP 
.SS "sbit SPI_RST_PIN = P3^5"

.PP
定义RST的管脚 
.PP
\fB待办事项\fP
.RS 4
定义RST的管脚 
.RE
.PP

.PP
在文件 \fBbsp_SPI\&.h\fP 第 \fB54\fP 行定义\&.
.SS "sbit SPI_SCK_PIN = P3^6"

.PP
定义SCK的管脚 
.PP
\fB待办事项\fP
.RS 4
定义SCK的管脚 
.RE
.PP

.PP
在文件 \fBbsp_SPI\&.h\fP 第 \fB46\fP 行定义\&.
.SS "sbit SPI_SDA_PIN = P3^4"

.PP
定义SDA的管脚 
.PP
\fB待办事项\fP
.RS 4
定义SDA的管脚 
.RE
.PP

.PP
在文件 \fBbsp_SPI\&.h\fP 第 \fB50\fP 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 bsp_XerolySkinner 的 源代码自动生成\&.
