.TH "D:/gitt/bsp_XerolySkinner/bsp_device 目录参考" 3 "2023年 三月 9日 星期四" "Version 1.0.0" "bsp_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/bsp_XerolySkinner/bsp_device 目录参考
.SH SYNOPSIS
.br
.PP
.SS "文件"

.in +1c
.ti -1c
.RI "文件 \fBbsp_IIC\&.c\fP"
.br
.RI "本类实现软件IIC功能 依此类派生出其他软件IIC功能 "
.ti -1c
.RI "文件 \fBbsp_IIC\&.h\fP"
.br
.RI "本类实现软件IIC功能 依此类派生出其他软件IIC功能 "
.ti -1c
.RI "文件 \fBbsp_SPI\&.c\fP"
.br
.RI "SPI的库 "
.ti -1c
.RI "文件 \fBbsp_SPI\&.h\fP"
.br
.RI "SPI的库 "
.ti -1c
.RI "文件 \fBbsp_UART\&.c\fP"
.br
.RI "UART的51库 "
.ti -1c
.RI "文件 \fBbsp_UART\&.h\fP"
.br
.RI "UART的51库 "
.in -1c
