.TH "D:/工作库/GitHub/bsp_XerolySkinner/bsp_device 目录参考" 3 "2023年 三月 9日 星期四" "Version 1.0.0" "bsp_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/工作库/GitHub/bsp_XerolySkinner/bsp_device 目录参考
.SH SYNOPSIS
.br
.PP
.SS "文件"

.in +1c
.ti -1c
.RI "文件 \fBbsp_IIC\&.c\fP"
.br
.ti -1c
.RI "文件 \fBbsp_IIC\&.h\fP"
.br
.ti -1c
.RI "文件 \fBbsp_SPI\&.c\fP"
.br
.ti -1c
.RI "文件 \fBbsp_SPI\&.h\fP"
.br
.ti -1c
.RI "文件 \fBbsp_UART\&.c\fP"
.br
.ti -1c
.RI "文件 \fBbsp_UART\&.h\fP"
.br
.in -1c
