.TH "todo" 3 "2023年 三月 10日 星期五" "Version 1.0.0" "bsp_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- 待办事项列表 
.PP

.IP "\fB成员 \fBIIC_SCK_PIN\fP \fP" 1c
定义SCK的管脚  
.IP "\fB成员 \fBIIC_SDA_PIN\fP \fP" 1c
定义SDA的管脚  
.IP "\fB成员 \fBSPI3_RST_PIN\fP \fP" 1c
定义RST的管脚  
.IP "\fB成员 \fBSPI3_SCK_PIN\fP \fP" 1c
定义SCK的管脚  
.IP "\fB成员 \fBSPI3_SDA_PIN\fP \fP" 1c
定义SDA的管脚  
.IP "\fB成员 \fBSPI4_CS_PIN\fP \fP" 1c
定义CS的管脚  
.IP "\fB成员 \fBSPI4_MISO_PIN\fP \fP" 1c
定义MISO的管脚  
.IP "\fB成员 \fBSPI4_MOSI_PIN\fP \fP" 1c
定义MOSI的管脚  
.IP "\fB成员 \fBSPI4_SCK_PIN\fP \fP" 1c
定义SCK的管脚 
.PP

