.TH "todo" 3 "2023年 三月 9日 星期四" "Version 1.0.0" "bsp_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- 待办事项列表 
.PP

.IP "\fB成员 \fBIIC_SCK_PIN\fP \fP" 1c
定义SCK的管脚  
.IP "\fB成员 \fBIIC_SDA_PIN\fP \fP" 1c
定义SDA的管脚  
.IP "\fB成员 \fBSPI_RST_PIN\fP \fP" 1c
定义RST的管脚  
.IP "\fB成员 \fBSPI_SCK_PIN\fP \fP" 1c
定义SCK的管脚  
.IP "\fB成员 \fBSPI_SDA_PIN\fP \fP" 1c
定义SDA的管脚 
.PP

