bsp_SPI.c
void SPI3_Byte(unsigned char temp)
使用总线发送一个字节数据
temp 发送的数据 无返回值 本函数为其他函数的子函数,不要直接使用本函数
References SPI3_SCK_PIN, SPI3_SDA_PIN.
Referenced by SPI3_ReadOneByte, SPI3_WriteOneByte.
void SPI3_WriteOneByte(unsigned char address, unsigned char dat)
使用总线发送一个字节数据
addr 需要改写的寄存器地址 dat 改写的数据 无返回值
References SPI3_Byte, SPI3_RST_PIN, SPI3_SCK_PIN.
unsigned char SPI3_ReadOneByte(unsigned char address)
使用总线获取一个字节数据
addr 需要接收的寄存器地址 dat 接受的数据 无返回值
References SPI3_Byte, SPI3_RST_PIN, SPI3_SCK_PIN, SPI3_SDA_PIN.
void SPI4_Init(void)
初始化4线SPI
无返回值 使用以下函数前,请先至少使用一次该函数初始化
References SPI4_CS_PIN, SPI4_SCK_PIN, SPI_CPOL, SPI_CS.
unsigned char SPI4_Byte(unsigned char temp)
使用总线交换一个字节数据
temp 发送的数据 交换回的数据
References SPI4_Delay, SPI4_MISO_PIN, SPI4_MOSI_PIN, SPI4_SCK_PIN, SPI_CPOL.
Referenced by SPI4_Data_WR.
void SPI4_Data_WR(const char *format,...)
使用总线交换一串数据
format 交换的格式 交换回的数据 以下为使用示例 //写入0xAB0xFF0xFF后,读取一个字节到dat中 SPI4_Data_WR("WWWR",0xAB,0xFF,0XFF,&dat);
References SPI4_Byte, SPI4_CS_PIN, SPI_CS.