bsp_IIC.h
@0
管脚复位状态
sbit IIC_SCK_PIN
定义SCK的管脚
待办事项定义SCK的管脚
Referenced by IIC_SCK.
sbit IIC_SDA_PIN
定义SDA的管脚
待办事项定义SDA的管脚
Referenced by IIC_SDA.
void IIC_WriteOneByte(unsigned char id, unsigned char addr, unsigned char dat)
IIC的基础实现方法
IIC的基础实现方法 id 发送的器件地址,如0x68(MPU6050) addr 需要改写的寄存器地址 dat 改写的数据 无返回值
References IIC_SendByte, IIC_Start, IIC_Stop, IIC_WaitAck.
unsigned char IIC_ReadOneByte(unsigned char id, unsigned char addr)
使用总线接收一个字节数据
id 接收的器件地址,如0x68(MPU6050) addr 需要获取数据的寄存器地址 返回该寄存器内的数据
References IIC_RecByte, IIC_SendAck, IIC_SendByte, IIC_Start, IIC_Stop, IIC_WaitAck.
void IIC_Write(unsigned char id, unsigned char addr, unsigned char *dat, unsigned int len)
使用总线发送定长数据
id 发送的器件地址,如0x68(MPU6050) addr 需要改写的寄存器地址起始 dat 改写的数据指针 len 数据数目 无返回值
References IIC_SendByte, IIC_Start, IIC_Stop, IIC_WaitAck.
void IIC_Read(unsigned char id, unsigned char addr, unsigned char *dat, unsigned int len)
使用总线接收定长数据
id 接收的器件地址,如0x68(MPU6050) addr 需要接收的寄存器地址起始 dat 改写的数据指针 len 数据数目 无返回值
References IIC_RecByte, IIC_SendAck, IIC_SendByte, IIC_Start, IIC_Stop, IIC_WaitAck.
void IIC_Start(void)
发送IIC开始信号
References IIC_Delay, IIC_RESET, IIC_SCK, IIC_SDA, IIC_SET.
Referenced by IIC_Read, IIC_ReadOneByte, IIC_Write, IIC_WriteOneByte.
void IIC_Stop(void)
发送IIC停止信号
References IIC_Delay, IIC_RESET, IIC_SCK, IIC_SDA, IIC_SET.
Referenced by IIC_Read, IIC_ReadOneByte, IIC_Write, IIC_WriteOneByte.
void IIC_SendAck(unsigned char ackbit)
发送IIC应答信号
ackbit 0为应答,1位非应答
References IIC_Delay, IIC_RESET, IIC_SCK, IIC_SDA, IIC_SET.
Referenced by IIC_Read, IIC_ReadOneByte.
unsigned char IIC_WaitAck(void)
等待应答信号
返回是否有回应
References IIC_Delay, IIC_READ, IIC_RESET, IIC_SCK, IIC_SDA, IIC_SET.
Referenced by IIC_Read, IIC_ReadOneByte, IIC_Write, IIC_WriteOneByte.
void IIC_SendByte(unsigned char byt)
发送IIC一个字节信号
byt 发送的字节
References IIC_Delay, IIC_RESET, IIC_SCK, IIC_SDA, IIC_SET.
Referenced by IIC_Read, IIC_ReadOneByte, IIC_Write, IIC_WriteOneByte.
unsigned char IIC_RecByte(void)
接收IIC一个字节信号
接收到的一个字节信号
References IIC_Delay, IIC_READ, IIC_RESET, IIC_SCK, IIC_SDA, IIC_SET.
Referenced by IIC_Read, IIC_ReadOneByte.
unsigned char IIC_SCK(unsigned char var)
控制SCK管脚口
var 此处有三个状态,IIC_SET置位管脚,IIC_RESET复位管脚 当var为IIC_READ时返回管脚状态 var 此处有三个状态,IIC_SET置位管脚,IIC_RESET复位管脚 当var为IIC_READ时返回管脚状态
References IIC_RESET, IIC_SCK_PIN, IIC_SET.
Referenced by IIC_RecByte, IIC_SendAck, IIC_SendByte, IIC_Start, IIC_Stop, IIC_WaitAck.
unsigned char IIC_SDA(unsigned char var)
控制SDA管脚口
var 此处有三个状态,IIC_SET置位管脚,IIC_RESET复位管脚 当var为IIC_READ时返回管脚状态 var 此处有三个状态,IIC_SET置位管脚,IIC_RESET复位管脚 当var为IIC_READ时返回管脚状态
References IIC_RESET, IIC_SDA_PIN, IIC_SET.
Referenced by IIC_RecByte, IIC_SendAck, IIC_SendByte, IIC_Start, IIC_Stop, IIC_WaitAck.
void IIC_Delay(void)
时序中的延时 在此处短暂延时
Referenced by IIC_RecByte, IIC_SendAck, IIC_SendByte, IIC_Start, IIC_Stop, IIC_WaitAck.